# Generated by Django 2.2 on 2019-05-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avaratrs/noavatar.png', null=True, upload_to='avatars/'),
        ),
    ]
