# Generated by Django 2.2 on 2019-05-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190516_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='blogapp/media/avaratrs/noavatar.png', null=True, upload_to='avatars/'),
        ),
    ]
