# Generated by Django 2.2 on 2019-05-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190516_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avaratrs/noavatar.png', null=True, upload_to='avatars/'),
        ),
    ]
