# Generated by Django 2.2 on 2019-05-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_newcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcomment',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='NewComment',
        ),
    ]
