# Generated by Django 2.2 on 2019-05-12 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_newcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewComment',
        ),
    ]
