# Generated by Django 2.2 on 2019-05-12 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_newcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcomment',
            name='from_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.Comment'),
        ),
    ]
