# Generated by Django 2.2 on 2019-05-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20190512_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newcomment',
            old_name='parent',
            new_name='new_parent',
        ),
    ]
