# Generated by Django 2.2 on 2019-05-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20190512_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newcomment',
            old_name='new_parent',
            new_name='parent',
        ),
    ]
