# Generated by Django 2.2 on 2019-05-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_remove_newcomment_from_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
