# Generated by Django 2.2 on 2019-12-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_auto_20191211_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcomment',
            name='text',
            field=models.TextField(max_length=120),
        ),
    ]
