# Generated by Django 2.2 on 2019-12-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_auto_20191222_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcomment',
            name='text',
            field=models.TextField(max_length=300),
        ),
    ]
