# Generated by Django 2.2 on 2019-12-27 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0023_auto_20191224_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['published_date']},
        ),
    ]
