# Generated by Django 2.2 on 2020-01-08 16:11

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0024_auto_20191227_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
        migrations.AddField(
            model_name='post',
            name='slug_date',
            field=autoslug.fields.AutoSlugField(blank=True, default=django.utils.timezone.now, editable=False, null=True, populate_from='created_date'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_title',
            field=autoslug.fields.AutoSlugField(blank=True, default='abc', editable=False, max_length=200, null=True, populate_from='title'),
        ),
    ]
