# Generated by Django 2.2 on 2020-01-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0027_auto_20200109_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='slug_category',
        ),
    ]
