# Generated by Django 2.2 on 2020-01-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0029_auto_20200112_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, default='Title', max_length=200),
        ),
    ]
