# Generated by Django 2.2 on 2020-01-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0030_auto_20200112_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='caption',
            field=models.CharField(blank=True, default='Caption', max_length=50),
        ),
    ]
