# Generated by Django 2.2 on 2020-01-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0031_auto_20200112_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total',
            field=models.DecimalField(decimal_places=2, default=32.0, max_digits=20),
        ),
    ]
