# Generated by Django 2.2 on 2020-01-15 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0034_post_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fee',
        ),
    ]
