# Generated by Django 2.2 on 2020-01-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200114_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=20),
        ),
    ]
