# Generated by Django 2.2 on 2020-01-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200116_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('hipped', 'Shipped'), ('created', 'Created'), ('refaunded', 'Refaunded')], default='created', max_length=120),
        ),
    ]
