# Generated by Django 2.2 on 2020-01-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200116_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('refaunded', 'Refaunded'), ('paid', 'Paid'), ('hipped', 'Shipped'), ('created', 'Created')], default='created', max_length=120),
        ),
    ]
